//
// Created by Peter Sun on 11/18/20.
//

#ifndef SEARCH_ENGINE_PETER_SUN_PORTER2_STEMMER_H
#define SEARCH_ENGINE_PETER_SUN_PORTER2_STEMMER_H


class porter2_stemmer {

};


#endif //SEARCH_ENGINE_PETER_SUN_PORTER2_STEMMER_H
